# Generated by Django 3.1.1 on 2020-10-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201004_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_published',
            new_name='isPublished',
        ),
    ]
